- uses: actions/checkout@master
- uses: arduino/setup-arduino-cli@v1.0.0
- run: |
    arduino-cli core update-index
    arduino-cli core install arduino:avr@1.8.2
    
    
    
- run: arduino-cli compile --fqbn arduino:avr:uno ./Arduino/Serial/Serial.ino --warnings more
